/**
 * Name → code lookup tables used to canonicalize a data row's region value
 * (clean-room, original data tables compiled from public ISO/USPS references).
 *
 * Keys are LOWERCASED names; values are LOWERCASED codes (postal / ISO alpha-2),
 * matching the lowercased join keys produced from the bundled GeoJSON.
 */

/** US state (+ DC + PR) full name → 2-letter USPS code. */
export const STATE_NAME_TO_CODE: Readonly<Record<string, string>> = {
  alabama: 'al',
  alaska: 'ak',
  arizona: 'az',
  arkansas: 'ar',
  california: 'ca',
  colorado: 'co',
  connecticut: 'ct',
  delaware: 'de',
  'district of columbia': 'dc',
  florida: 'fl',
  georgia: 'ga',
  hawaii: 'hi',
  idaho: 'id',
  illinois: 'il',
  indiana: 'in',
  iowa: 'ia',
  kansas: 'ks',
  kentucky: 'ky',
  louisiana: 'la',
  maine: 'me',
  maryland: 'md',
  massachusetts: 'ma',
  michigan: 'mi',
  minnesota: 'mn',
  mississippi: 'ms',
  missouri: 'mo',
  montana: 'mt',
  nebraska: 'ne',
  nevada: 'nv',
  'new hampshire': 'nh',
  'new jersey': 'nj',
  'new mexico': 'nm',
  'new york': 'ny',
  'north carolina': 'nc',
  'north dakota': 'nd',
  ohio: 'oh',
  oklahoma: 'ok',
  oregon: 'or',
  pennsylvania: 'pa',
  'rhode island': 'ri',
  'south carolina': 'sc',
  'south dakota': 'sd',
  tennessee: 'tn',
  texas: 'tx',
  utah: 'ut',
  vermont: 'vt',
  virginia: 'va',
  washington: 'wa',
  'west virginia': 'wv',
  wisconsin: 'wi',
  wyoming: 'wy',
  'puerto rico': 'pr',
};

/**
 * Country full name → ISO-3166-1 alpha-2 code. A practical subset covering common
 * countries plus several common aliases (e.g. "usa", "uk"). Unknown names fall
 * through unchanged and simply won't match a feature.
 */
export const COUNTRY_NAME_TO_CODE: Readonly<Record<string, string>> = {
  afghanistan: 'af',
  albania: 'al',
  algeria: 'dz',
  angola: 'ao',
  argentina: 'ar',
  armenia: 'am',
  australia: 'au',
  austria: 'at',
  azerbaijan: 'az',
  bahamas: 'bs',
  bahrain: 'bh',
  bangladesh: 'bd',
  belarus: 'by',
  belgium: 'be',
  belize: 'bz',
  benin: 'bj',
  bhutan: 'bt',
  bolivia: 'bo',
  'bosnia and herzegovina': 'ba',
  botswana: 'bw',
  brazil: 'br',
  brunei: 'bn',
  bulgaria: 'bg',
  'burkina faso': 'bf',
  burundi: 'bi',
  cambodia: 'kh',
  cameroon: 'cm',
  canada: 'ca',
  chad: 'td',
  chile: 'cl',
  china: 'cn',
  colombia: 'co',
  'costa rica': 'cr',
  croatia: 'hr',
  cuba: 'cu',
  cyprus: 'cy',
  czechia: 'cz',
  'czech republic': 'cz',
  'democratic republic of the congo': 'cd',
  denmark: 'dk',
  djibouti: 'dj',
  'dominican republic': 'do',
  ecuador: 'ec',
  egypt: 'eg',
  'el salvador': 'sv',
  'equatorial guinea': 'gq',
  eritrea: 'er',
  estonia: 'ee',
  eswatini: 'sz',
  ethiopia: 'et',
  fiji: 'fj',
  finland: 'fi',
  france: 'fr',
  gabon: 'ga',
  gambia: 'gm',
  georgia: 'ge',
  germany: 'de',
  ghana: 'gh',
  greece: 'gr',
  greenland: 'gl',
  guatemala: 'gt',
  guinea: 'gn',
  'guinea-bissau': 'gw',
  guyana: 'gy',
  haiti: 'ht',
  honduras: 'hn',
  hungary: 'hu',
  iceland: 'is',
  india: 'in',
  indonesia: 'id',
  iran: 'ir',
  iraq: 'iq',
  ireland: 'ie',
  israel: 'il',
  italy: 'it',
  'ivory coast': 'ci',
  "cote d'ivoire": 'ci',
  jamaica: 'jm',
  japan: 'jp',
  jordan: 'jo',
  kazakhstan: 'kz',
  kenya: 'ke',
  kosovo: 'xk',
  kuwait: 'kw',
  kyrgyzstan: 'kg',
  laos: 'la',
  latvia: 'lv',
  lebanon: 'lb',
  lesotho: 'ls',
  liberia: 'lr',
  libya: 'ly',
  lithuania: 'lt',
  luxembourg: 'lu',
  madagascar: 'mg',
  malawi: 'mw',
  malaysia: 'my',
  mali: 'ml',
  mauritania: 'mr',
  mexico: 'mx',
  moldova: 'md',
  mongolia: 'mn',
  montenegro: 'me',
  morocco: 'ma',
  mozambique: 'mz',
  myanmar: 'mm',
  burma: 'mm',
  namibia: 'na',
  nepal: 'np',
  netherlands: 'nl',
  'new zealand': 'nz',
  nicaragua: 'ni',
  niger: 'ne',
  nigeria: 'ng',
  'north korea': 'kp',
  'north macedonia': 'mk',
  macedonia: 'mk',
  norway: 'no',
  oman: 'om',
  pakistan: 'pk',
  panama: 'pa',
  'papua new guinea': 'pg',
  paraguay: 'py',
  peru: 'pe',
  philippines: 'ph',
  poland: 'pl',
  portugal: 'pt',
  qatar: 'qa',
  'republic of the congo': 'cg',
  congo: 'cg',
  romania: 'ro',
  russia: 'ru',
  'russian federation': 'ru',
  rwanda: 'rw',
  'saudi arabia': 'sa',
  senegal: 'sn',
  serbia: 'rs',
  'sierra leone': 'sl',
  singapore: 'sg',
  slovakia: 'sk',
  slovenia: 'si',
  somalia: 'so',
  'south africa': 'za',
  'south korea': 'kr',
  korea: 'kr',
  'south sudan': 'ss',
  spain: 'es',
  'sri lanka': 'lk',
  sudan: 'sd',
  suriname: 'sr',
  sweden: 'se',
  switzerland: 'ch',
  syria: 'sy',
  taiwan: 'tw',
  tajikistan: 'tj',
  tanzania: 'tz',
  thailand: 'th',
  togo: 'tg',
  'trinidad and tobago': 'tt',
  tunisia: 'tn',
  turkey: 'tr',
  turkiye: 'tr',
  turkmenistan: 'tm',
  uganda: 'ug',
  ukraine: 'ua',
  'united arab emirates': 'ae',
  uae: 'ae',
  'united kingdom': 'gb',
  uk: 'gb',
  'great britain': 'gb',
  'united states': 'us',
  'united states of america': 'us',
  usa: 'us',
  'u.s.a.': 'us',
  'u.s.': 'us',
  america: 'us',
  uruguay: 'uy',
  uzbekistan: 'uz',
  venezuela: 've',
  vietnam: 'vn',
  yemen: 'ye',
  zambia: 'zm',
  zimbabwe: 'zw',
};
